// AUTH
const Backoffice = {
  LOGIN: 'AUTH_BO_LOGIN',
  LOGIN_SUCCEEDED: 'AUTH_BO_LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'AUTH_BO_LOGIN_FAILED',
  LOGOUT: 'AUTH_BO_LOGOUT',
  REGISTER: 'AUTH_BO_REGISTER',
  REGISTER_SUCCEEDED: 'AUTH_BO_REGISTER_SUCCEEDED',
  REGISTER_FAILED: 'AUTH_BO_REGISTER_FAILED',
  FORGET_PASSWORD: 'AUTH_BO_FORGET_PASSWORD',
  FORGET_PASSWORD_SUCCEEDED: 'AUTH_BO_FORGET_PASSWORD_SUCCEEDED',
  FORGET_PASSWORD_FAILED: 'AUTH_BO_FORGET_PASSWORD_FAILED'
};

const BuyerSeller = {
  LOGIN: 'AUTH_BS_LOGIN',
  LOGIN_SUCCEEDED: 'AUTH_BS_LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'AUTH_BS_LOGIN_FAILED',
  LOGOUT: 'AUTH_BS_LOGOUT',
  REGISTER: 'AUTH_BS_REGISTER',
  REGISTER_SUCCEEDED: 'AUTH_BS_REGISTER_SUCCEEDED',
  REGISTER_FAILED: 'AUTH_BS_REGISTER_FAILED',
  FORGET_PASSWORD: 'AUTH_BS_FORGET_PASSWORD',
  FORGET_PASSWORD_SUCCEEDED: 'AUTH_BS_FORGET_PASSWORD_SUCCEEDED',
  FORGET_PASSWORD_FAILED: 'AUTH_BS_FORGET_PASSWORD_FAILED',
  UPDATE_USER_DATA: 'UPDATE_BS_DATA'
};

export default {
  Backoffice,
  BuyerSeller
};
