const NIUBIZ = {
  GET_SECURITY_REQUEST: 'GET_SECURITY_REQUEST',
  GET_SECURITY_SUCCEEDED: 'GET_SECURITY_SUCCEEDED',
  GET_SECURITY_FAILED: 'GET_SECURITY_FAILED',

  POST_ECOMMERCE_REQUEST: 'POST_ECOMMERCE_REQUEST',
  POST_ECOMMERCE_SUCCEEDED: 'POST_ECOMMERCE_SUCCEEDED',
  POST_ECOMMERCE_FAILED: 'POST_ECOMMERCE_FAILED',

  POST_AUTHORIZATION_REQUEST: 'POST_AUTHORIZATION_REQUEST',
  POST_AUTHORIZATION_SUCCEEDED: 'POST_AUTHORIZATION_SUCCEEDED',
  POST_AUTHORIZATION_FAILED: 'POST_AUTHORIZATION_FAILED'
};

export default NIUBIZ;
